### ISSUE TITLE
Primo with multiple related outcomes in overlapping samples

### ISSUE THREAD

**Issue by anamariaUIC** [kjgleason/primo#5]
Hello,

I was wondering do you recommend using this software with metabolite QTL summary statistics. In my scenario I have 3 related outcomes (coming from diabetic retinopathy). I don't have GWAS data. I will just have QTL summary statistics, genotypes and phenotypes for 3  related outcomes. I am using the same cohort to analyze those 3 outcomes (so they are overlapping samples). Can your software help me **determine which QTLs would be specific or shared across those 3 outcomes**? In your paper I read that your software doesn't have problem with overlapping samples, please confirm. Also is there is issue with related phenotypes (outcomes) like in my case?

I downloaded codes used in your paper and in order to run this code can I just replace each of the bellow QTL summary statistics with summary statistics calculated for every of my outcomes? Or should I proceed differently?  

##=== determine SNPs present in all studies ===##
esnp <- unique(cis.eQTL.res$SNP)
msnp <- unique(cis.meQTL.res$SNP)
psnp <- unique(cis.pQTL.res$SNP)

Also I am planning to put Primo in my grant proposal. Can you please tell me with this paragraph is applicable for analysis I plan to do (above):

"Due to pleiotropic effects of SNPs and linkage disequilibrium (LD) among SNPs in a region, it is commonly observed that SNPs are associated with multiple molecular and/or complex traits ref, ref. In order to probabilistically assess if the same mQTL within a locus is likely to be causally contributing to multiple outcomes we can use the multi-omics colocalization method Primo ref. Primo will help to account for linkage disequilibrium LD by enabling conditional association analyses in gene regions harboring known trait-associated SNPs."

Thank you so much for looking into this,
Ana

**Comment by kjgleason** [comment]
Hi Ana:
Thanks for your interest. I'm not sure I fully understand your data as described, but the software should work with metabolite QTL summary statistics, or more generally with summary statistics of the effects of SNPs/variants on downstream traits (molecular or complex). It should help estimate the probabilities of which trait(s) each SNP/variant is associated with.  The software can be applied to data from overlapping samples (it uses summary staistics with lower probability of being associated with any outcome to estimate the correlation due to sample overlap).  Related phenotypes should be fine, though I haven't evaluated performance in settings where correlations between phenotypes are close to 1.

You likely can proceed in similar fashion to the code you downloaded by replacing cis.eQTL.res with your first set of summary statistics, cis.meQTL.res with your second set, etc. See also the tutorial included with the package.

Best,
Kevin
